Partially revert #1576
The GitHub action fails because it cannot run with the necessary
permissions: it requires write access to be able to post a comment,
but when triggered from a fork, the token is limited to read access.

The error is from the thollander/actions-comment-pull-request action:

    No comment has been found with asked pattern. Creating a new comment.
    Error: Resource not accessible by integration

The downgrading of the token is explained on:

  https://docs.github.com/en/actions/security-guides/automatic-token-authentication

where “Maximum access for pull requests from public forked
repositories” says that the pull-requests permission is capped at read
in the typical case for us.

I kept the underlying functionality since we might want to use it for
something else (perhaps track the duration in the README).

Fixes the errors seen on the recent PRs: #1693, #1687, and likely
others.