Make library mutable in book-library exercise
Otherwise the library cannot have changes added to it when testing via main.

Compile error:
```
error[E0596]: cannot borrow `library` as mutable, as it is not declared as mutable
```

I could definitely be missing something, but I also tried compiling with the given solution (with main uncommented) and received the same error.