bazel: handle copying of read-only files
With #3197, `cargo xtask` began copying binaries produced by Bazel to
`~/.cargo/bin/`. These binaries are read-only files since Bazel likes
to mark everything in its `bazel-bin/` directory as read-only.

As the files entered the cache on GitHub, our builds started failing,
see thse jobs from unrelated PRs:

-
https://github.com/google/comprehensive-rust/actions/runs/27474258285/job/81210548383
-
https://github.com/google/comprehensive-rust/actions/runs/27474256814/job/81210554918

They fail with

```
[695 / 698] Compiling Rust rlib mdbook-course-lib (6 files); 0s disk-cache, processwrapper-sandbox
INFO: Found 2 targets...
INFO: Elapsed time: 93.311s, Critical Path: 21.20s
INFO: 698 processes: 261 disk cache hit, 306 internal, 131 processwrapper-sandbox.
INFO: Build completed successfully, 698 total actions
Error: Permission denied (os error 13)
Error: Process completed with exit code 1.
```

which is what I see locally as well when I run the `cargo xtask
install-tools` on `main`.